# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egda_ui_QMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 343)
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 79, 421, 161))
        font = QtGui.QFont()
        font.setFamily("Cantarell Extra Bold")
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setProperty("value", 123.4)
        self.lcdNumber.setObjectName("lcdNumber")
        self.butStart = QtWidgets.QPushButton(self.centralwidget)
        self.butStart.setGeometry(QtCore.QRect(160, 249, 80, 27))
        self.butStart.setObjectName("butStart")
        self.butStop = QtWidgets.QPushButton(self.centralwidget)
        self.butStop.setGeometry(QtCore.QRect(250, 249, 80, 27))
        self.butStop.setObjectName("butStop")
        self.butExit = QtWidgets.QPushButton(self.centralwidget)
        self.butExit.setGeometry(QtCore.QRect(380, 250, 80, 27))
        self.butExit.setObjectName("butExit")
        self.linePortName = QtWidgets.QLineEdit(self.centralwidget)
        self.linePortName.setGeometry(QtCore.QRect(40, 249, 113, 26))
        self.linePortName.setObjectName("linePortName")
        self.valueTarget = QtWidgets.QLCDNumber(self.centralwidget)
        self.valueTarget.setGeometry(QtCore.QRect(31, 10, 101, 61))
        self.valueTarget.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.valueTarget.setFont(font)
        self.valueTarget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.valueTarget.setProperty("value", 123.4)
        self.valueTarget.setObjectName("valueTarget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(12, 82, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox::indicator { width: 20px; height: 20px;}")
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(24, 24))
        self.checkBox.setCheckable(False)
        self.checkBox.setObjectName("checkBox")
        self.slideTarget = QtWidgets.QSlider(self.centralwidget)
        self.slideTarget.setGeometry(QtCore.QRect(150, 30, 241, 22))
        self.slideTarget.setMaximum(1000)
        self.slideTarget.setSingleStep(5)
        self.slideTarget.setPageStep(50)
        self.slideTarget.setOrientation(QtCore.Qt.Horizontal)
        self.slideTarget.setObjectName("slideTarget")
        self.butUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.butUpdate.setGeometry(QtCore.QRect(400, 28, 61, 27))
        self.butUpdate.setObjectName("butUpdate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRead = QtWidgets.QAction(MainWindow)
        self.actionRead.setObjectName("actionRead")
        self.actionWrite = QtWidgets.QAction(MainWindow)
        self.actionWrite.setObjectName("actionWrite")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuConfig.addAction(self.actionRead)
        self.menuConfig.addAction(self.actionWrite)
        self.menuHelp_2.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.linePortName, self.butStart)
        MainWindow.setTabOrder(self.butStart, self.butStop)
        MainWindow.setTabOrder(self.butStop, self.butExit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EGDA"))
        self.butStart.setText(_translate("MainWindow", "Start"))
        self.butStop.setText(_translate("MainWindow", "Stop"))
        self.butExit.setText(_translate("MainWindow", "Exit"))
        self.linePortName.setText(_translate("MainWindow", "COM3"))
        self.butUpdate.setText(_translate("MainWindow", "Update"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.menuHelp_2.setTitle(_translate("MainWindow", "Help"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRead.setText(_translate("MainWindow", "Read"))
        self.actionWrite.setText(_translate("MainWindow", "Write"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

